apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-rs
spec:
  selector:
    matchLabels:
      env: test
  replicas: 2 # Actual should match desired
  template:
    metadata:
      name: new-rs-pod
      labels:
        env: test # and condition
    spec:
      containers:
      - image: nginx
        name: testnginx
